import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* inline script to set theme early to avoid flash-of-incorrect-theme */}
        <script dangerouslySetInnerHTML={{ __html: `
          (function(){
            try{
              var t = localStorage.getItem('theme');
              if(t) document.documentElement.setAttribute('data-theme', t);
              else document.documentElement.setAttribute('data-theme', 'dark');
            }catch(e){}
          })();
        `}} />
        {children}
      </body>
    </html>
  );
}
