import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatWidget from './components/ChatWidget';
import { LanguageProvider } from './lib/LanguageProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* force dark theme early to avoid flash-of-incorrect-theme */}
        <script dangerouslySetInnerHTML={{ __html: `
          (function(){
            try{
              document.documentElement.setAttribute('data-theme', 'dark');
              // initialize language from localStorage (default: it)
              var lang = (function(){
                try{ return localStorage.getItem('site-lang') || 'it' }catch(e){ return 'it' }
              })();
              document.documentElement.setAttribute('data-lang', lang);
              document.documentElement.lang = lang;
            }catch(e){}
          })();
        `}} />
        {/* LanguageProvider wraps the app so client components can access translations */}
        <LanguageProvider>
          {children}
          <ChatWidget />
        </LanguageProvider>
      </body>
    </html>
  );
}
